name: mopay_ewallet
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  intl: ^0.19.0
  sliver_tools:
  awesome_dialog: ^3.2.0
  dotted_line: ^3.2.2
  smooth_page_indicator:
  flutter_barcode_scanner:
  icons_plus: ^4.0.0
  image_picker: ^1.0.4
  image: ^4.1.3
  dio: ^5.4.3+1
  flutter_dotenv: ^5.1.0
  rxdart: ^0.28.0
  shared_preferences: ^2.2.3
  carousel_slider_plus: ^6.0.0
  jwt_decode: ^0.3.1
  lottie: ^3.1.2
  collection: ^1.18.0
  firebase_messaging: ^15.0.2
  flutter_local_notifications: ^17.2.1
  flutter_native_splash: ^2.4.0
  firebase_core: ^3.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#850000"
  image: assets/images/logo-mopay/logo4.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-mopay/mopay_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo-mopay/
    - assets/images/logo/
    - assets/images/slider/
    - assets/images/background/
    - assets/images/profile-pic/
    - assets/lottie/
    - .env
